version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plannerx
    ports:
      - "3399:3306"
    networks:
      mynet:
        aliases:
          - mysql.docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8099:80"
    networks:
      mynet:
        aliases:
          - phpmyadmin.docker
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    depends_on:
      - db
    networks:
      mynet:
        aliases:
          - plannerx.docker
    command: sh docker/run.sh
    ports:
      - 8085:8085
      - 35729:35729
      - 5005:5005
networks:
  mynet:
    driver: bridge