version: '3.3'
services:
  #  mysqldb:
  #    container_name: mysql-service
  #    image: 'mysql/mysql-server:5.7'
  #    volumes:
  #      - ./dbdata:/var/lib/mysql
  #    environment:
  #      MYSQL_DATABASE: plannerx
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_ROOT_HOST: '%'
  #    ports:
  #      - '3303:3303'
  #    restart: always
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh docker/run.sh
    ports:
      - 8085:8085
      - 35729:35729
      - 5005:5005